name: Build and Deploy

on:
  push:
    branches:
      - main # Exécute le workflow sur chaque push vers main

jobs:
  # Étape 1 : Build l'image Docker
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/employee-api-cloud:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/employee-api-cloud:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/employee-api-cloud:latest

  # Étape 2 : Push l'image Docker vers Docker Hub
  push:
    runs-on: ubuntu-latest
    needs: build # Ce job dépend de l'étape "build"
    steps:
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/employee-api-cloud:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/employee-api-cloud:latest

  # Étape 3 : Déploiement sur Google Cloud Run
  deploy:
    runs-on: ubuntu-latest
    needs: push # Ce job dépend de l'étape "push"
    steps:
      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy my-app-service \
          --image ${{ secrets.DOCKER_HUB_USERNAME }}/employee-api-cloud:${{ github.sha }} \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated
